import { Organization, ActivityLogEntry, PendingApproval } from '../types/team';

// Mock Organization Data
export const MOCK_ORGANIZATION: Organization = {
  id: 'org-001',
  name: 'TechCorp Industries',
  logo: 'https://images.unsplash.com/photo-1549923746-c502d488b3ea?w=200&h=200&fit=crop',
  website: 'https://techcorp.com',
  industry: 'Technology',
  size: '50-200 employees',
  masterProfileId: 'master-001',
  subscriptionTier: 'premium',
  createdAt: new Date('2024-01-15'),
  billingEmail: 'billing@techcorp.com',
  members: [
    {
      id: 'master-001',
      email: 'sarah.johnson@techcorp.com',
      name: 'Sarah Johnson',
      role: 'master',
      permissions: [],
      invitedBy: 'system',
      invitedAt: new Date('2024-01-15'),
      status: 'active',
      lastActive: new Date('2025-11-07T10:30:00'),
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    },
    {
      id: 'member-001',
      email: 'john.recruiter@techcorp.com',
      name: 'John Recruiter',
      role: 'member',
      roleTemplate: 'full_recruiter',
      permissions: [
        'jobs.create',
        'jobs.edit',
        'jobs.delete',
        'jobs.publish',
        'candidates.view',
        'candidates.contact',
        'candidates.rank',
        'candidates.move',
        'interviews.schedule',
        'interviews.manage',
        'messaging.send',
        'calendar.view',
        'calendar.manage',
        'analytics.view',
      ],
      invitedBy: 'master-001',
      invitedAt: new Date('2024-01-20'),
      status: 'active',
      departmentId: 'dept-001',
      lastActive: new Date('2025-11-07T09:15:00'),
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    },
    {
      id: 'member-002',
      email: 'lisa.manager@techcorp.com',
      name: 'Lisa Manager',
      role: 'member',
      roleTemplate: 'hiring_manager',
      permissions: [
        'candidates.view',
        'candidates.rank',
        'interviews.schedule',
        'messaging.send',
        'calendar.view',
      ],
      invitedBy: 'master-001',
      invitedAt: new Date('2024-02-01'),
      status: 'active',
      assignedJobs: ['job-001', 'job-002'],
      departmentId: 'dept-001',
      lastActive: new Date('2025-11-06T16:45:00'),
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    },
    {
      id: 'member-003',
      email: 'mike.interviewer@techcorp.com',
      name: 'Mike Interviewer',
      role: 'member',
      roleTemplate: 'interviewer',
      permissions: [
        'candidates.view',
        'interviews.schedule',
        'calendar.view',
        'messaging.send',
      ],
      invitedBy: 'master-001',
      invitedAt: new Date('2024-02-10'),
      status: 'active',
      departmentId: 'dept-001',
      lastActive: new Date('2025-11-07T08:00:00'),
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    },
    {
      id: 'member-004',
      email: 'emma.hr@techcorp.com',
      name: 'Emma HR',
      role: 'member',
      roleTemplate: 'hr_admin',
      permissions: [
        'jobs.create',
        'jobs.edit',
        'jobs.publish',
        'candidates.view',
        'analytics.view',
        'analytics.export',
        'calendar.view',
      ],
      invitedBy: 'master-001',
      invitedAt: new Date('2024-01-25'),
      status: 'active',
      departmentId: 'dept-002',
      lastActive: new Date('2025-11-07T07:30:00'),
      avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop',
    },
    {
      id: 'member-005',
      email: 'pending@techcorp.com',
      name: 'David Pending',
      role: 'member',
      roleTemplate: 'interviewer',
      permissions: [
        'candidates.view',
        'interviews.schedule',
        'calendar.view',
        'messaging.send',
      ],
      invitedBy: 'master-001',
      invitedAt: new Date('2025-11-05'),
      status: 'pending',
      departmentId: 'dept-001',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    },
  ],
  departments: [
    {
      id: 'dept-001',
      name: 'Engineering',
      description: 'Technical recruitment team',
      color: '#3b82f6',
      memberIds: ['member-001', 'member-002', 'member-003', 'member-005'],
      createdAt: new Date('2024-01-20'),
      createdBy: 'master-001',
    },
    {
      id: 'dept-002',
      name: 'Human Resources',
      description: 'HR and administrative team',
      color: '#ec4899',
      memberIds: ['member-004'],
      createdAt: new Date('2024-01-25'),
      createdBy: 'master-001',
    },
    {
      id: 'dept-003',
      name: 'Sales & Marketing',
      description: 'Sales recruitment team',
      color: '#14b8a6',
      memberIds: [],
      createdAt: new Date('2024-03-01'),
      createdBy: 'master-001',
    },
  ],
  settings: {
    requireApprovalForJobs: false,
    allowMemberInvites: false,
    defaultMemberPermissions: ['candidates.view', 'calendar.view'],
    notificationPreferences: {
      newApplications: true,
      teamActivity: true,
      systemUpdates: true,
    },
  },
};

// Mock Activity Log
export const MOCK_ACTIVITY_LOG: ActivityLogEntry[] = [
  {
    id: 'log-001',
    userId: 'member-001',
    userName: 'John Recruiter',
    action: 'Created new job posting',
    targetType: 'job',
    targetId: 'job-001',
    targetName: 'Senior React Developer',
    details: 'Posted in Engineering department',
    timestamp: new Date('2025-11-07T09:15:00'),
    metadata: { department: 'Engineering', status: 'Active' },
  },
  {
    id: 'log-002',
    userId: 'member-002',
    userName: 'Lisa Manager',
    action: 'Ranked candidate',
    targetType: 'candidate',
    targetId: 'cand-001',
    targetName: 'Alex Thompson',
    details: 'Moved to Interview stage',
    timestamp: new Date('2025-11-07T08:45:00'),
    metadata: { previousStage: 'Review', newStage: 'Interview' },
  },
  {
    id: 'log-003',
    userId: 'master-001',
    userName: 'Sarah Johnson',
    action: 'Invited team member',
    targetType: 'team',
    targetId: 'member-005',
    targetName: 'David Pending',
    details: 'Invited as Interviewer',
    timestamp: new Date('2025-11-05T14:30:00'),
    metadata: { role: 'Interviewer', department: 'Engineering' },
  },
  {
    id: 'log-004',
    userId: 'member-004',
    userName: 'Emma HR',
    action: 'Exported analytics report',
    targetType: 'settings',
    details: 'Monthly recruitment metrics',
    timestamp: new Date('2025-11-06T11:00:00'),
    metadata: { reportType: 'Monthly', format: 'PDF' },
  },
  {
    id: 'log-005',
    userId: 'member-003',
    userName: 'Mike Interviewer',
    action: 'Scheduled interview',
    targetType: 'candidate',
    targetId: 'cand-002',
    targetName: 'Jamie Lee',
    details: 'Technical interview on Nov 10',
    timestamp: new Date('2025-11-07T07:20:00'),
    metadata: { date: '2025-11-10', time: '14:00', type: 'Technical' },
  },
  {
    id: 'log-006',
    userId: 'master-001',
    userName: 'Sarah Johnson',
    action: 'Created department',
    targetType: 'department',
    targetId: 'dept-003',
    targetName: 'Sales & Marketing',
    details: 'New recruitment department',
    timestamp: new Date('2024-03-01T10:00:00'),
    metadata: { memberCount: 0 },
  },
  {
    id: 'log-007',
    userId: 'member-001',
    userName: 'John Recruiter',
    action: 'Updated job status',
    targetType: 'job',
    targetId: 'job-002',
    targetName: 'Product Manager',
    details: 'Changed status to Closed',
    timestamp: new Date('2025-11-06T16:30:00'),
    metadata: { previousStatus: 'Active', newStatus: 'Closed' },
  },
  {
    id: 'log-008',
    userId: 'member-002',
    userName: 'Lisa Manager',
    action: 'Contacted candidate',
    targetType: 'candidate',
    targetId: 'cand-003',
    targetName: 'Chris Martin',
    details: 'Sent interview invitation',
    timestamp: new Date('2025-11-06T15:15:00'),
    metadata: { method: 'Email' },
  },
];

// Mock Pending Approvals
export const MOCK_PENDING_APPROVALS: PendingApproval[] = [
  {
    id: 'approval-001',
    type: 'job_posting',
    requestedBy: 'member-001',
    requestedByName: 'John Recruiter',
    requestedAt: new Date('2025-11-07T09:00:00'),
    status: 'pending',
    details: {
      jobTitle: 'Senior Python Developer',
      department: 'Engineering',
      salary: '$120k - $150k',
    },
  },
  {
    id: 'approval-002',
    type: 'member_access_request',
    requestedBy: 'member-003',
    requestedByName: 'Mike Interviewer',
    requestedAt: new Date('2025-11-06T14:30:00'),
    status: 'pending',
    details: {
      requestedPermissions: ['candidates.move', 'candidates.rank'],
      reason: 'Need to manage candidate pipeline',
    },
  },
];

// Mock Jobs for testing (simplified)
export const MOCK_JOBS = [
  {
    id: 'job-001',
    title: 'Senior React Developer',
    department: 'Engineering',
    status: 'Active',
    applicants: 24,
    createdBy: 'member-001',
    createdAt: new Date('2025-10-15'),
  },
  {
    id: 'job-002',
    title: 'Product Manager',
    department: 'Engineering',
    status: 'Closed',
    applicants: 45,
    createdBy: 'member-001',
    createdAt: new Date('2025-09-20'),
  },
  {
    id: 'job-003',
    title: 'UX Designer',
    department: 'Engineering',
    status: 'Active',
    applicants: 18,
    createdBy: 'member-004',
    createdAt: new Date('2025-11-01'),
  },
];

// Mock Candidates (simplified)
export const MOCK_CANDIDATES = [
  {
    id: 'cand-001',
    name: 'Alex Thompson',
    jobId: 'job-001',
    stage: 'Interview',
    appliedAt: new Date('2025-10-20'),
  },
  {
    id: 'cand-002',
    name: 'Jamie Lee',
    jobId: 'job-001',
    stage: 'Review',
    appliedAt: new Date('2025-10-25'),
  },
  {
    id: 'cand-003',
    name: 'Chris Martin',
    jobId: 'job-003',
    stage: 'Shortlist',
    appliedAt: new Date('2025-11-02'),
  },
];
